### ISSUE TITLE
The App is not running when deployed on Bluemix using "cf push" command

### ISSUE THREAD

**Issue by UrmiSahoo** [watson-developer-cloud/text-bot#16]
1. I have changed the .env file with Alchemy_api_key, Conversation, Weather and Cloudant   credentials.
2. In the manifest.yml file I have specified a different name under applications and I have mentioned the services under application as well. 
3. The training data is also present. 
4. The app works fine in the Bluemix console but doesn't respond when deployed to Bluemix.

**Comment by kognate** [comment]
Can you post the output of  `cf logs --recent`  please?

**Comment by UrmiSahoo** [comment]
urmis-mbp-2:text-bot urmibhakta$ cf logs weather-conversation-bot1 --recent
Connected, dumping recent logs for app weather-conversation-bot1 in org Watson_chatbot1 / space Watson_chatbot1 as Urmi.Bhakta@ibm.com...

2016-10-28T09:42:56.83-0400 [RTR/1]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:56.811 +0000] "GET / HTTP/1.1" 304 0 0 "https://console.ng.bluemix.net/dashboard/applications/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.154:24290 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:140b0b85-82fe-401e-4e01-27f14debda2f response_time:0.023799531 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"361097025"
2016-10-28T09:42:56.91-0400 [RTR/3]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:56.907 +0000] "GET /css/style.css HTTP/1.1" 304 0 0 "https://weather-conversation-bot1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.154:26097 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:795c777f-4734-4d3a-40d4-c9dcea60d05f response_time:0.007115443 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"2650227463"
2016-10-28T09:42:56.98-0400 [RTR/1]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:56.979 +0000] "GET /js/common.js HTTP/1.1" 304 0 0 "https://weather-conversation-bot1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.154:24290 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:1acb2af4-539b-4bfc-4d63-18a007fe440c response_time:0.003326968 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"3248846735"
2016-10-28T09:42:57.05-0400 [RTR/2]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:57.046 +0000] "GET /js/api.js HTTP/1.1" 304 0 0 "https://weather-conversation-bot1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.153:44222 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:2c75af58-ec4e-4826-5d73-e74a0bca845a response_time:0.005154477 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"2650227703"
2016-10-28T09:42:57.11-0400 [RTR/0]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:57.110 +0000] "GET /js/payload.js HTTP/1.1" 304 0 0 "https://weather-conversation-bot1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.153:14825 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:89777ff5-d7ac-4dd8-4f5c-6c190455b82d response_time:0.003848518 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"361097649"
2016-10-28T09:42:57.11-0400 [RTR/1]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:57.109 +0000] "GET /js/conversation.js HTTP/1.1" 304 0 0 "https://weather-conversation-bot1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.156:47298 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:b3779d2e-33f4-4e12-7a85-28d557f966e6 response_time:0.005796436 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"737526607"
2016-10-28T09:42:57.18-0400 [RTR/0]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:57.180 +0000] "GET /js/global.js HTTP/1.1" 304 0 0 "https://weather-conversation-bot1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.153:15079 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:fc74dc7c-b787-4ab9-6e30-d87168a7e147 response_time:0.005615103 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"2650227831"
2016-10-28T09:42:57.20-0400 [RTR/0]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:57.198 +0000] "GET /images/icon-sms.svg HTTP/1.1" 304 0 0 "https://weather-conversation-bot1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.153:16972 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:1fd88c9d-9612-4d16-7304-475da1d66a06 response_time:0.006760312 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"361097745"
2016-10-28T09:42:57.20-0400 [RTR/0]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:57.201 +0000] "GET /images/x.svg HTTP/1.1" 304 0 0 "https://weather-conversation-bot1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.153:15282 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:e68e6cd4-8540-4a65-4d87-f46752831e51 response_time:0.004585248 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"361097761"
2016-10-28T09:42:57.28-0400 [App/0]      ERR Fri, 28 Oct 2016 13:42:57 GMT bot:controller 1. Process new message: {
2016-10-28T09:42:57.28-0400 [App/0]      ERR   "text": "Hello"
2016-10-28T09:42:57.28-0400 [App/0]      ERR }.
2016-10-28T09:42:57.29-0400 [RTR/1]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:57.245 +0000] "GET /images/icon-fb.svg HTTP/1.1" 304 0 0 "https://weather-conversation-bot1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.154:25374 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:22b2a68a-c5b1-40b4-653e-479656635756 response_time:0.047903217 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"361097937"
2016-10-28T09:42:57.72-0400 [App/0]      ERR /home/vcap/app/lib/api/alchemy-language.js:53
2016-10-28T09:42:57.72-0400 [App/0]      ERR       debug('text: %s, entities: %s', params.text, JSON.stringify(response.entities));
2016-10-28T09:42:57.72-0400 [App/0]      ERR                                                                           ^
2016-10-28T09:42:57.72-0400 [App/0]      **ERR TypeError: Cannot read property 'entities' of null**
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at /home/vcap/app/lib/api/alchemy-language.js:53:75
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at /home/vcap/app/node_modules/watson-developer-cloud/lib/alchemy_error_formatter.js:34:7
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at Request._callback (/home/vcap/app/node_modules/watson-developer-cloud/lib/requestwrapper.js:82:5)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at Request.self.callback (/home/vcap/app/node_modules/watson-developer-cloud/node_modules/request/request.js:187:22)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at emitTwo (events.js:87:13)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at Request.emit (events.js:172:7)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at Request.<anonymous> (/home/vcap/app/node_modules/watson-developer-cloud/node_modules/request/request.js:1044:10)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at emitOne (events.js:77:13)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at Request.emit (events.js:169:7)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/watson-developer-cloud/node_modules/request/request.js:965:12)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at emitNone (events.js:72:20)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at IncomingMessage.emit (events.js:166:7)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at endReadableNT (_stream_readable.js:921:12)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at nextTickCallbackWith2Args (node.js:442:9)
2016-10-28T09:42:57.72-0400 [App/0]      ERR     at process._tickCallback (node.js:356:17)
2016-10-28T09:42:57.75-0400 [RTR/2]      OUT weather-conversation-bot1.mybluemix.net - [28/10/2016:13:42:57.248 +0000] "POST /api/message HTTP/1.1" 502 72 67 "https://weather-conversation-bot1.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36" 108.168.250.155:23757 x_forwarded_for:"129.42.208.182" x_forwarded_proto:"https" vcap_request_id:462ceca0-fe50-4525-73f1-01cc31926be7 response_time:0.502273634 app_id:dd6661dc-678d-40d4-a7c0-86b37f36747c x_global_transaction_id:"737527023"
2016-10-28T09:42:57.77-0400 [App/0]      ERR npm ERR! Linux 3.19.0-33-generic
2016-10-28T09:42:57.77-0400 [App/0]      ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
2016-10-28T09:42:57.77-0400 [App/0]      ERR npm ERR! node v4.6.0
2016-10-28T09:42:57.77-0400 [App/0]      ERR npm ERR! npm  v3.10.9
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR! code ELIFECYCLE
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR! text-bot@0.1.2 start: `node server.js`
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR! Exit status 1
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR! 
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR! Failed at the text-bot@0.1.2 start script 'node server.js'.
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR! If you do, this is most likely a problem with the text-bot package,
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR! not with npm itself.
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR! Tell the author that this fails on your system:
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR!     node server.js
2016-10-28T09:42:57.78-0400 [App/0]      ERR npm ERR! You can get information on how to open an issue for this project with:
2016-10-28T09:42:57.79-0400 [App/0]      ERR npm ERR!     npm bugs text-bot
2016-10-28T09:42:57.79-0400 [App/0]      ERR npm ERR! Or if that isn't available, you can get their info via:
2016-10-28T09:42:57.79-0400 [App/0]      ERR npm ERR!     npm owner ls text-bot
2016-10-28T09:42:57.79-0400 [App/0]      ERR npm ERR! There is likely additional logging output above.
2016-10-28T09:42:57.80-0400 [App/0]      ERR npm ERR! Please include the following file with any support request:
2016-10-28T09:42:57.80-0400 [App/0]      ERR npm ERR!     /home/vcap/app/npm-debug.log
2016-10-28T09:42:57.95-0400 [API/7]      OUT App instance exited with guid dd6661dc-678d-40d4-a7c0-86b37f36747c payload: {"cc_partition"=>"default", "droplet"=>"dd6661dc-678d-40d4-a7c0-86b37f36747c", "version"=>"d381838c-8746-415f-afab-d48f29a11843", "instance"=>"227017b8d05b4bba986007d9046199b5", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1477662177}
2016-10-28T09:43:28.39-0400 [DEA/151]    OUT Starting app instance (index 0) with guid dd6661dc-678d-40d4-a7c0-86b37f36747c
2016-10-28T09:43:46.86-0400 [App/0]      OUT 
2016-10-28T09:43:46.86-0400 [App/0]      OUT > text-bot@0.1.2 start /home/vcap/app
2016-10-28T09:43:46.86-0400 [App/0]      OUT > node server.js
2016-10-28T09:43:47.76-0400 [App/0]      ERR Fri, 28 Oct 2016 13:43:47 GMT bot:server Initializing WebUI
2016-10-28T09:43:47.77-0400 [App/0]      ERR Fri, 28 Oct 2016 13:43:47 GMT bot:server Server listening on port: 64583
2016-10-28T09:43:47.93-0400 [App/0]      OUT Uploaded stats { ok: true }
urmis-mbp-2:text-bot urmibhakta$ clear

**Comment by lkrishnamurthy** [comment]
Urmi : Like we discussed, need to edit the .env file with the WEATHER_URL property empty as well as the cloudant db 'botdb' create.

**Comment by lkrishnamurthy** [comment]
Fixed #19.  I updated the README instructions as well as enabled botdb to be auto created if one doesn't exist in Cloudant. The Weather URL is fixed as well.
